version: 2.1

## Aliases

executor-auth-aws: &executor-auth-aws
  aws_auth:
    aws_access_key_id: $AWS_ACCESS_KEY_ID
    aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

ignore-master: &ignore-master
  filters:
    branches:
      ignore:
        - master

## ORBS
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

## WORKFLOWS

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: circleci-ecr-orb-demo
          tag: "$CIRCLE_SHA1"
          <<: *ignore-master
          <<: *executor-auth-aws